name: tests

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go mod download
      - env:
          SYS11DBAAS_ORGANIZATION: ${{ secrets.ACCEPTANCETESTSORGANIZATION }}
          SYS11DBAAS_PROJECT: ${{ secrets.ACCEPTANCETESTSPROJECT }}
          SYS11DBAAS_API_KEY: ${{ secrets.ACCEPTANCETESTSAPIKEY }}
        run: |
          TF_ACC=1 go test -parallel 8 -timeout 60m -v ./...
 

