name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go mod download
      - env:
          SYS11DBAAS_ORGANIZATION: ${{ secrets.ACCEPTANCETESTSORGANIZATION }}
          SYS11DBAAS_PROJECT: ${{ secrets.ACCEPTANCETESTSPROJECT }}
          SYS11DBAAS_API_KEY: ${{ secrets.ACCEPTANCETESTSAPIKEY }}
        run: |
          TF_ACC=1 go test -parallel 8 -timeout 60m -v ./...
 

